apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-binding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-servcieaccount
    namespace: argo-workflows
roleRef:
  kind: Role
  name: argo-role
  apiGroup: rbac.authorization.k8s.io