apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
  namespace: argo-workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - "*"
    verbs:
      - get
      - patch
      - create
      - list
      - delete